12-03-2024-12:48:49

diff --git a/ZSH_LIB_UTILS/yts b/ZSH_LIB_UTILS/yts
--- a/ZSH_LIB_UTILS/yts
+++ b/ZSH_LIB_UTILS/yts
@@ -151,7 +151,6 @@ action_do () {
 
 		unsetopt localtraps # Initialize CTRL-c trap
 		trap kill_job INT
-		#stty -echo
 
 		ERROR_CNT=0
 		start_job ${URL}
@@ -262,7 +261,7 @@ action_do () {
 			if grep -qi 'eta.*error' <<<${LOG_LINE};then # Contains both - split
 				ETA=$(sed -E 's/([0-9])(\[.*)/\1\n\2/g' <<<${LOG_LINE} | head -1 | str_trim)
 				ERR=$(sed -E 's/([0-9])(\[.*)/\1\n\2/g' <<<${LOG_LINE} | tail -1 | str_trim)
-			elif grep -qi 'eta' <<<${LOG_LINE};then
+			elif grep -q 'ETA' <<<${LOG_LINE};then # Uppercase ETA
 				echo "${0}: GOT ETA ${LOG_LINE}" >> ${_YTS_DBG_LOG}
 				ETA=${LOG_LINE}
 			elif grep -qi 'error' <<<${LOG_LINE};then
@@ -294,8 +293,8 @@ action_do () {
 			if [[ -n ${ETA} && ${ETA_COMPLETE} == 'false' ]];then
 				case ${ETA:l} in
 					*'100% of'*) LINE_COLOR='<B><g>';ETA_COMPLETE=true;;; # Prevent doubling complete line
-					*mib/s*) LINE_COLOR='<w>';;
-					*kib/s*) LINE_COLOR='<B><y>';;
+					*mib/s*) LINE_COLOR='<w>';show_pos_rate;;
+					*kib/s*) LINE_COLOR='<B><y>';show_pos_rate;;
 					*) continue;; # Skip other
 				esac
 			else
@@ -326,7 +325,6 @@ action_do () {
 		clear_log "action_do"
 		sleep 1 # Job request delay
 	done # List complete
-	#stty echo
 
 	for M in ${_MARKED};do
 		[[ ${_DOWNLOADS[${M}]} == 'true' ]] && list_set_selected ${M} ${_GHOST_ROW} || list_set_selected ${M} ${_AVAIL_ROW}
@@ -793,6 +791,7 @@ log_find () {
 	local BOT=${2} # Page bot row
 	local AU='' # Author
 	local FN='' # Filename
+	local TITLE=''
 	local TM=''
 	local LINE=''
 	local R=0
@@ -807,7 +806,8 @@ log_find () {
 		AU=$(get_field author ${R}) # Author
 		TM=$(sed -E 's/^.*ago\s+(.*)\)/\1/' <<<$(get_field agetime ${R})) # Video length
 		TM=$(tr -d '[()]' <<<${TM} | sed 's/undefined//')
-		LINE=$(grep -i ${AU:=null} ${_DOWNLOAD_LOG} | grep ${TM:=null}) # Match on author/time
+		TITLE=$(get_field title ${R}) # Title
+		LINE=$(grep -i ${AU:=null} ${_DOWNLOAD_LOG} | grep ${TM:=null} | grep ${TITLE}) # Match on author/time/title
 		if [[ -n ${LINE} ]];then 
 			FN=$(cut -d '|' -f3 <<<${LINE})
 			[[ ${SEEN[${FN}]} == 'true' ]] && continue # Only process a filename once
@@ -892,14 +892,7 @@ post_process () {
 	} >>${_ERROR_LOG} 2>/dev/null
 }
 
-reset_job () {
-	[[ ${_DEBUG} -ge ${_YTS_DBG} ]] && dbg "${functrace[1]} called ${0}:${LINENO}: ARGC:${#@}"
-
-	kill_job
-	msg_box -t${_ALERT_TM} -x${_ALERT_COORDS[X]} -y${_ALERT_COORDS[Y]} "<m>Job Restarted<N>"
-}
-
-rumble () {
+query_rumble () {
 	local SEARCHTERM=${1}
 	local -A LAST_MSG=($(box_coords_get ${_LAST_MSG_TAG}))
 	local -a AGES
@@ -954,7 +947,6 @@ rumble () {
 			AGE=$(sed 's/ago .*/ago/' <<<${AGES[${X}]})
 			[[ -z ${AGE} ]] && continue
 			[[ ! ${AGE} =~ 'ago' ]] && continue # Dump junk listings without age
-			[[ ${g_QUERY_KEY:l} == ${TITLES[${X}]:l} ]] && continue # Experimental to avoid garbage
 			VID_LIST+="${g_QUERY_KEY}|${TITLES[${X}]}|${AGE}|${LINKS[${X}]}|${DURATIONS[${X}]}" # Unique rows
 		done
 	else # General search
@@ -971,7 +963,7 @@ rumble () {
 		CHANNELS=("${(f)$(pup --charset utf8 '.video-item--by-a attr{href}' <<<${PG})}")
 
 		for ((X=1; X<=${#TITLES}; X++));do
-			[[ ${CHANNELS[${X}]} =~ 'user' ]] && continue # Experimental to avoid duplicates
+			[[ ${CHANNELS[${X}]} =~ 'user' ]] && echo "Query:${g_QUERY_KEY} Skipped ${TITLES[${X}]} ${CHANNELS[${X}]}" >> /tmp/gen_filter.dbg && continue # Filter
 			AGE=$(sed 's/T.*//' <<<${AGES[${X}]})
 			CHANNEL=$(sed 's#^.*/##' <<<${CHANNELS[${X}]})
 			VID_LIST+="${CHANNEL}|${TITLES[${X}]}|${AGE}|${LINKS[${X}]}|${DURATIONS[${X}]}" # Unique rows
@@ -999,6 +991,93 @@ rumble () {
 	fi
 
 	return 0
+}
+
+query_youtube () { 
+	local -a SORT_LIST
+	local AUTHOR=''
+	local CUSTOM_KEY=false
+	local DATA=false
+	local HIT=false
+	local LINE=''
+	local NDX=0
+	local PROXY_CMD=''
+	local STR=''
+	local TITLE=''
+	local L
+
+	[[ ${_DEBUG} -ge ${_YTS_DBG} ]] && dbg "${functrace[1]} called ${0}:${LINENO}: ARGC:${#@} ARGV:${@}"
+
+	if [[ -n ${g_QUERY_KEY} ]];then
+		[[ ${g_ENGINE_KEY:l} == 'yns' ]] && g_PROXY_CMD=${g_PROXY_CMD:s/-s//} && g_STRICT=false # No strict requested
+		PROXY_CMD="${g_PROXY_CMD} ${g_QUERY_KEY:q}"
+	else
+		PROXY_CMD="${g_PROXY_CMD}"
+	fi
+
+	[[ ${_DEBUG} -ge ${_YTS_DBG} ]] && dbg "${0}:${LINENO} g_QUERY_KEY:${g_QUERY_KEY}"
+	[[ ${_DEBUG} -ge ${_YTS_DBG} ]] && dbg "${0}:${LINENO} g_ENGINE_KEY:${g_ENGINE_KEY}"
+	[[ ${_DEBUG} -ge ${_YTS_DBG} ]] && dbg "${0}:${LINENO} ${WHITE_FG}STRICT${RESET}:${g_STRICT}"
+	[[ ${_DEBUG} -ge ${_YTS_DBG} ]] && dbg "${0}:${LINENO} ${WHITE_FG}PROXY COMMAND${RESET}:${PROXY_CMD}"
+
+	_LOCAL_LIST=()
+
+	NDX=0
+	while read LINE;do
+		[[ ${LINE:l} =~ 'matched' ]] && DATA=true && continue
+
+		[[ ${LINE:l} =~ 'usage' && ${DATA} != 'true' ]] && exit_leave
+		[[ ${LINE:l} =~ 'error' && ${DATA} != 'true' ]] && exit_leave $(msg_exit E "${PROXY_CMD} returned an error")
+
+		((NDX++))
+		[[ ${LINE:l} =~ 'rejected' ]] && _REJECTS[${NDX}]=true || _REJECTS[${NDX}]=false
+
+		STR=$(iconv -f utf-8 -t ascii//translit <<<${LINE}) # Scrub non ascii
+		STR=${STR:s/Streamed //}
+
+		[[ ${g_ENGINE_KEY:l} =~ 'p' ]] && CUSTOM_KEY=true
+
+		# --- BEGIN Experimental filtering
+		if [[ ${CUSTOM_KEY} == 'false' ]];then
+			g_SEARCH_TYPE='channel'
+			HIT=false
+			AUTHOR=$(cut -d'|' -f2 <<<${LINE})
+			[[ ${AUTHOR:l} =~ ${g_DISPLAY_KEY:l} ]] && HIT=true
+			[[ ${AUTHOR:l} =~ ${g_QUERY_KEY:l} ]] && HIT=true
+			[[ ${AUTHOR:gs/ //:l} =~ ${g_QUERY_KEY:l} ]] && HIT=true
+			[[ ${_DEBUG} -ge ${_YTS_DBG} ]] && dbg "${0}:${LINENO} EXPERIMENTAL FILTERING AUTHOR:${AUTHOR} HIT:${HIT}"
+			[[ ${HIT} == 'false' ]] && continue
+			# --- END Experimental filtering
+		else
+			g_SEARCH_TYPE='general'
+		fi
+		 
+		[[ ${_REJECTS[${NDX}]} == 'false' && ${DATA} == 'true' ]] && _LOCAL_LIST+=${STR}
+	done< <(eval ${PROXY_CMD})
+
+	[[ ${g_STRICT} == 'true' ]] && g_STRICT_MSG="$(total_rejects ${NDX})" || g_STRICT_MSG=''
+
+	[[ ${_DEBUG} -ge ${_YTS_DBG} ]] && dbg "${0}:${LINENO} _LOCAL_LIST count: ${#_LOCAL_LIST}"
+	[[ ${_DEBUG} -ge ${_YTS_DBG} ]] && dbg "${0}:${LINENO} _LOCAL_LIST content:\n $(for L in ${_LOCAL_LIST};do echo ${L};done)"
+
+	[[ ${_SMCUP} == 'false' ]] && do_smcup
+
+	# Return search status
+	if ! arr_is_populated "${_LOCAL_LIST}";then
+		g_PROXY_CMD=$(str_trim ${(Q)g_PROXY_CMD})
+
+		msg_box -H2 -p -PK "<r>No data for query<N>:${g_PROXY_CMD}|${g_STRICT_MSG}|Omit option '<w>-S<N>' to disable strict filtering"
+		return 1
+	fi
+
+	return 0
+}
+
+reset_job () {
+	[[ ${_DEBUG} -ge ${_YTS_DBG} ]] && dbg "${functrace[1]} called ${0}:${LINENO}: ARGC:${#@}"
+
+	kill_job
+	msg_box -t${_ALERT_TM} -x${_ALERT_COORDS[X]} -y${_ALERT_COORDS[Y]} "<m>Job Restarted<N>"
 }
 
 select_download () {
@@ -1081,6 +1160,10 @@ set_item_color () {
 	esac
 }
 
+show_pos_rate () {
+	tput cup ${_ALERT_COORDS[X]} $((_ALERT_COORDS[Y] +6));echo -n "${BOLD}${GREEN_FG}⇊ ⇊ ⇊ ⇊ ⇊ ⇊${RESET}"
+}
+
 start_job () {
 	local URL=${@}
 	local CMD=''
@@ -1125,86 +1208,6 @@ total_rejects () {
 	[[ ${TL_RJ} -ne 0 ]] && RJ_PCT=$(( (TL_RJ/TL_VIDS) * 100 ))
 
 	echo "${RJ_PCT}%"
-}
-
-youtube () { 
-	local -a SORT_LIST
-	local AUTHOR=''
-	local CUSTOM_KEY=false
-	local DATA=false
-	local HIT=false
-	local LINE=''
-	local NDX=0
-	local PROXY_CMD=''
-	local STR=''
-	local TITLE=''
-	local L
-
-	[[ ${_DEBUG} -ge ${_YTS_DBG} ]] && dbg "${functrace[1]} called ${0}:${LINENO}: ARGC:${#@} ARGV:${@}"
-
-	if [[ -n ${g_QUERY_KEY} ]];then
-		[[ ${g_ENGINE_KEY:l} == 'yns' ]] && g_PROXY_CMD=${g_PROXY_CMD:s/-s//} && g_STRICT=false # No strict requested
-		PROXY_CMD="${g_PROXY_CMD} ${g_QUERY_KEY:q}"
-	else
-		PROXY_CMD="${g_PROXY_CMD}"
-	fi
-
-	[[ ${_DEBUG} -ge ${_YTS_DBG} ]] && dbg "${0}:${LINENO} g_QUERY_KEY:${g_QUERY_KEY}"
-	[[ ${_DEBUG} -ge ${_YTS_DBG} ]] && dbg "${0}:${LINENO} g_ENGINE_KEY:${g_ENGINE_KEY}"
-	[[ ${_DEBUG} -ge ${_YTS_DBG} ]] && dbg "${0}:${LINENO} ${WHITE_FG}STRICT${RESET}:${g_STRICT}"
-	[[ ${_DEBUG} -ge ${_YTS_DBG} ]] && dbg "${0}:${LINENO} ${WHITE_FG}PROXY COMMAND${RESET}:${PROXY_CMD}"
-
-	_LOCAL_LIST=()
-
-	NDX=0
-	while read LINE;do
-		[[ ${LINE:l} =~ 'matched' ]] && DATA=true && continue
-
-		[[ ${LINE:l} =~ 'usage' && ${DATA} != 'true' ]] && exit_leave
-		[[ ${LINE:l} =~ 'error' && ${DATA} != 'true' ]] && exit_leave $(msg_exit E "${PROXY_CMD} returned an error")
-
-		((NDX++))
-		[[ ${LINE:l} =~ 'rejected' ]] && _REJECTS[${NDX}]=true || _REJECTS[${NDX}]=false
-
-		STR=$(iconv -f utf-8 -t ascii//translit <<<${LINE}) # Scrub non ascii
-		STR=${STR:s/Streamed //}
-
-		[[ ${g_ENGINE_KEY:l} =~ 'p' ]] && CUSTOM_KEY=true
-
-		# --- BEGIN Experimental filtering
-		if [[ ${CUSTOM_KEY} == 'false' ]];then
-			g_SEARCH_TYPE='channel'
-			HIT=false
-			AUTHOR=$(cut -d'|' -f2 <<<${LINE})
-			[[ ${AUTHOR:l} =~ ${g_DISPLAY_KEY:l} ]] && HIT=true
-			[[ ${AUTHOR:l} =~ ${g_QUERY_KEY:l} ]] && HIT=true
-			[[ ${AUTHOR:gs/ //:l} =~ ${g_QUERY_KEY:l} ]] && HIT=true
-			[[ ${_DEBUG} -ge ${_YTS_DBG} ]] && dbg "${0}:${LINENO} EXPERIMENTAL FILTERING AUTHOR:${AUTHOR} HIT:${HIT}"
-			[[ ${HIT} == 'false' ]] && continue
-			# --- END Experimental filtering
-		else
-			g_SEARCH_TYPE='general'
-		fi
-		 
-		[[ ${_REJECTS[${NDX}]} == 'false' && ${DATA} == 'true' ]] && _LOCAL_LIST+=${STR}
-	done< <(eval ${PROXY_CMD})
-
-	[[ ${g_STRICT} == 'true' ]] && g_STRICT_MSG="$(total_rejects ${NDX})" || g_STRICT_MSG=''
-
-	[[ ${_DEBUG} -ge ${_YTS_DBG} ]] && dbg "${0}:${LINENO} _LOCAL_LIST count: ${#_LOCAL_LIST}"
-	[[ ${_DEBUG} -ge ${_YTS_DBG} ]] && dbg "${0}:${LINENO} _LOCAL_LIST content:\n $(for L in ${_LOCAL_LIST};do echo ${L};done)"
-
-	[[ ${_SMCUP} == 'false' ]] && do_smcup
-
-	# Return search status
-	if ! arr_is_populated "${_LOCAL_LIST}";then
-		g_PROXY_CMD=$(str_trim ${(Q)g_PROXY_CMD})
-
-		msg_box -H2 -p -PK "<r>No data for query<N>:${g_PROXY_CMD}|${g_STRICT_MSG}|Omit option '<w>-S<N>' to disable strict filtering"
-		return 1
-	fi
-
-	return 0
 }
 
 #--Begin GetOpts--
@@ -1367,7 +1370,7 @@ if [[ ${#} -eq 0 ]];then # NO args passed
 		fav_get
 		if [[ -n ${g_QUERY_KEY} ]];then
 			msg_box "Requesting videos for <B><I>${g_DISPLAY_KEY}<N>..."
-			${g_QRY_ENGINE} ${g_QUERY_KEY} # Call the extractor
+			query_${g_QRY_ENGINE} ${g_QUERY_KEY} # Call the extractor
 			 
 			if [[ ${?} -eq 0 ]];then
 				select_download ${g_QUERY_KEY}
@@ -1377,7 +1380,7 @@ if [[ ${#} -eq 0 ]];then # NO args passed
 else # Args passed
 	_CMD_LINE_ARGS=true
 	g_QUERY_KEY="${@}"
-	${g_QRY_ENGINE} ${g_QUERY_KEY}
+	query_${g_QRY_ENGINE} ${g_QUERY_KEY}
 	if [[ ${?} -eq 0 ]];then
 		fav_set ${g_QUERY_KEY}
 		select_download ${g_QUERY_KEY}
