05-03-2024-10:29:45

diff --git a/ZSH_LIB_UTILS/yts b/ZSH_LIB_UTILS/yts
--- a/ZSH_LIB_UTILS/yts
+++ b/ZSH_LIB_UTILS/yts
@@ -21,21 +21,22 @@ YELLOW_FG="\033[33m"
 WHITE_ON_GREY="\033[0m\033[0;1;37;100m"
 
 #Declarations
-typeset -a _LOCAL_LIST
-typeset -A _FAVORITE_ENGINE
+typeset -A COORDS=(X 15 Y 38 H 10 W 86)
 typeset -A _DOWNLOADS
 typeset -A _FAILED
-typeset -A _FUTURE
+typeset -A _FAVORITE_ENGINE
 typeset -A _FIELD_LEN
-typeset -A _STATUS_MSGS
+typeset -A _FUTURE
 typeset -A _REJECTS
-typeset -A COORDS=(X 15 Y 38 H 10 W 86)
+typeset -A _STATUS_MSGS
+typeset -a _LOCAL_LIST
 
 #Constants
 #_JS_SCRIPT=./yts.js
 _ACTION=download
 _DOWNLOAD_DIR=~/Downloads
 _ERROR_LIMIT=15
+_ERROR_LOG=/tmp/yts.err
 _FIELD_LEN[age]=30
 _FIELD_LEN[agetime]=40
 _FIELD_LEN[author]=26
@@ -103,6 +104,7 @@ action_do () {
 	local SCAN_MAX=10
 	local STALLS=0
 	local TITLE
+	local AUTHOR
 	local URL
 
 	msg_box_clear
@@ -189,21 +191,20 @@ action_do () {
 						ERROR_CNT=0 # reset
 						break 2
 					fi
+					AUTHOR=$(get_field author ${M})	
 					case ${L:l} in
 						*giving\ up*)	ERROR_CNT=${_ERROR_LIMIT}	
 											break 2 # while loop
 						;;
-						*network\ is\ unreachable*|*retrying*|*operation\ timed\ out*)	msg_box -t.2 -x$((COORDS[X]+5)) -y$((COORDS[Y] + COORDS[W] -27)) "<r>Network Errors <w>${ERROR_CNT}<N>"
+						*network\ is\ unreachable*|*retrying*|*operation\ timed\ out*)	
+							msg_box -t.2 -x$((COORDS[X]+5)) -y$((COORDS[Y] + COORDS[W] -27)) "<r>Network Errors<w>${ERROR_CNT}<N>"
+							echo "${AUTHOR} - Caught:"${L: -65} >> ${_ERROR_LOG}
 							((ERROR_CNT++))
 							HAD_ERROR=true
 						;;
-						*for\ reading*)
+						*) msg_box -t.2 -x$((COORDS[X]+5)) -y$((COORDS[Y] + COORDS[W] -27)) "<r>Network Errors<w>${ERROR_CNT}<N>"
+							echo "${AUTHOR} - Uncaught:"${L: -65} >> ${_ERROR_LOG}
 							((ERROR_CNT++))
-							msg_box -t.2 -x$((COORDS[X]+5)) -y$((COORDS[Y] + COORDS[W] -27)) "<r>Download Stalled <w>${ERROR_CNT}<N>"
-							HAD_ERROR=true
-						;;
-						*) ((ERROR_CNT++))
-							msg_box -t.2 -x$((COORDS[X]+5)) -y$((COORDS[Y] + COORDS[W] -27)) "<r>Network Errors <w>${ERROR_CNT}<N>"
 							HAD_ERROR=true
 						;;
 					esac
@@ -256,6 +257,7 @@ action_do () {
 
 		done
 		NDX=0
+		clear_log "action_do"
 	done
 	stty echo
 
@@ -271,8 +273,6 @@ action_do () {
 	_MARKED=()
 	
 	trap - INT #Downloads are finished; nothing to interrupt
-
-	clear_log "action_do"
 
 	return 0
 }
@@ -345,7 +345,14 @@ get_favorite () {
 
 		case ${_SELECTION_KEY} in
 			d) delete_favorite ${_SELECTION_VALUE} && _DISPLAY_LIST=() && continue;;
-			l) { [[ ${g_QRY_ENGINE} == 'rumble' && ${g_LIVE_OPT} == 'true' ]] && g_LIVE_OPT=false || g_LIVE_OPT=true } && continue;;
+			l) if [[ ${g_QRY_ENGINE} == 'rumble' ]];then
+					[[ ${g_LIVE_OPT} == 'true' ]] && g_LIVE_OPT=false || g_LIVE_OPT=true
+				else
+					msg_box -p -PK "Livestream toggle only applies to Rumble"
+					g_LIVE_OPT=true
+				fi
+				continue
+				;;
 			r) g_QRY_ENGINE='rumble' && continue;;
 			y) g_QRY_ENGINE='youtube' && continue;;
 		esac
@@ -383,138 +390,150 @@ get_field () {
 			time) STR=$(cut -d'|' -f5 <<<${_LIST[${NDX}]});STR="(${STR})";;
 			agetime) STR=$(cut -d'|' -f1,5 <<<${_LIST[${NDX}]});STR="(${STR:s/|/ /})";;
 		esac
-	fi
+		fi
 
-	[[ ${_DEBUG} -gt 2 ]] && dbg "${0}:${LINENO} Returning STR:${STR}"
+		[[ ${_DEBUG} -gt 2 ]] && dbg "${0}:${LINENO} Returning STR:${STR}"
 
-	STR=$(iconv -f utf-8 -t ascii//translit <<<${STR}) #Scrub non ascii
-	echo -n ${STR[1,65]}
-}
+		STR=$(iconv -f utf-8 -t ascii//translit <<<${STR}) #Scrub non ascii
+		echo -n ${STR[1,65]}
+	}
 
-item_decorate () {
-	local NDX=${1}
-	local STR
+	item_decorate () {
+		local NDX=${1}
+		local STR
 
-	if [[ ${_DOWNLOADS[${NDX}]} == 'true' ]];then
-		STR="Downloaded..."
-	elif [[ ${_FAILED[${NDX}]} == 'true' ]];then
-		STR="Failed..."
-	elif [[ ${_FUTURE[${NDX}]} == 'true' ]];then
-		STR="Future..."
-	else
-		STR="$(get_field agetime ${NDX})"
-	fi
+		if [[ ${_DOWNLOADS[${NDX}]} == 'true' ]];then
+			STR="Downloaded..."
+		elif [[ ${_FAILED[${NDX}]} == 'true' ]];then
+			STR="Failed..."
+		elif [[ ${_FUTURE[${NDX}]} == 'true' ]];then
+			STR="Future..."
+		else
+			STR="$(get_field agetime ${NDX})"
+		fi
 
-	echo -n ${STR[1,${_FIELD_LEN[agetime]}]}
-}
+		echo -n ${STR[1,${_FIELD_LEN[agetime]}]}
+	}
 
-kill_job () {
-	local JOB
-	local RC
+	kill_job () {
+		local JOB
+		local RC
 
-	JOB=$(ps -h -p ${g_PID})
-	RC=$?
-	
-	if [[ ${RC} -eq 0 ]];then
-		kill -9 ${g_PID} >/dev/null 2>&1
-	else
-		echo "No process found for PID:${g_PID}" >> ${g_LOG}
-	fi
+		JOB=$(ps -h -p ${g_PID})
+		RC=$?
+		
+		if [[ ${RC} -eq 0 ]];then
+			kill -9 ${g_PID} >/dev/null 2>&1
+		else
+			echo "No process found for PID:${g_PID}" >> ${g_LOG}
+		fi
 
-	if [[ ! ${functrace[1]} =~ "reset_job" ]];then
-		trap - INT # disable trap
-		clear_log "kill_job"
-		exit_leave "${_SCRIPT}:${WHITE_FG}Download Job${RESET}:${JOB} ${WHITE_FG}was ${RED_FG}killed${RESET}"
-	fi
-}
+		if [[ ! ${functrace[1]} =~ "reset_job" ]];then
+			trap - INT # disable trap
+			clear_log "kill_job"
+			exit_leave "${_SCRIPT}:${WHITE_FG}Download Job${RESET}:${JOB} ${WHITE_FG}was ${RED_FG}killed${RESET}"
+		fi
+	}
 
-post_process () {
-	local -a KEYWORDS=("judge_napolitano_-_" "official" "afshin_rattansi_s_" "the_" "_show")
-	local K
+	post_process () {
+		local -a KEYWORDS=("judge_napolitano_-_" "official" "afshin_rattansi_s_" "the_" "_show")
+		local K
 
-	msg_box "Post processing..."
+		msg_box "Post processing..."
 
-	for K in ${KEYWORDS};do
-		fsub -iy ${K} ${_DOWNLOAD_DIR} >/dev/null 2>&1
-	done
-}
-
-reset_job () {
-	kill_job
-	msg_box -t.2 -x$((COORDS[X]+5)) -y$((COORDS[Y] + COORDS[W] -25)) "<m>Job Restarted<N>"
-}
-
-rumble () {
-	local SEARCHTERM=${@}
-	local -a AGES
-	local -a CHANNELS
-	local -a DURATIONS
-	local -a LINKS
-	local -a TITLES
-	local -a VID_LIST=()
-	local AGE
-	local CHANNEL
-	local GEN_SEARCH
-	local LIVE
-	local PG
-	local MSG
-	local X
-
-	PG=$(wget -q -O - "http://rumble.com/c/${SEARCHTERM}?page=1")
-
-	if [[ -n ${PG} ]];then # channel search
-		[[ ${_FAVORITE_ENGINE[${SEARCHTERM}]:l} == 'r' ]] && g_LIVE=false
-		[[ ${_FAVORITE_ENGINE[${SEARCHTERM}]:l} == 'rl' ]] && g_LIVE=true
-		[[ ${g_LIVE_OPT} == 'true' ]] && { [[ ${g_LIVE} == 'true' ]] && g_LIVE=false || g_LIVE=true }
-		[[ ${g_LIVE} == 'true' ]] && MSG="Searching for livestreams" || MSG="Searching for videos"
-		msg_box -c ${MSG}
-		LIVE=$(pup '.channel-subheader--menu-item attr{href}' <<<${PG} | grep "livestreams")
-		[[ ${g_LIVE} == 'true' && -n ${LIVE} ]] && PG=$(wget -q -O - "http://rumble.com${LIVE}")
-		[[ ${PG:l} =~ "no videos found" ]] && msg_box -c "<r>No livestreams<N> for ${SEARCHTERM}|Falling back to defaults..." && PG=$(wget -q -O - "http://rumble.com/c/${SEARCHTERM}?page=1")
-
-		g_SEARCH_TYPE=channel
-		TITLES=("${(f)$(pup --charset utf8 '.title__link text{}' <<<${PG} | tut blank_lines | iconv -f utf-8 -t ascii//TRANSLIT | sed 's/|//g')}")
-		AGES=("${(f)$(pup --charset utf8 '.videostream__data text{}' <<<${PG} | tut blank_lines | tr '[\012|\015]' '[ ]' | sed -e 's/comments /comments\n/g')}")
-		LINKS=("${(f)$(pup --charset utf8 'a.videostream__link attr{href}' <<<${PG})}")
-		DURATIONS=("${(f)$(pup --charset utf8 '.videostream__badge text{}' <<<${PG} | tut blank_lines)}")
-
-		for ((X=1; X<=${#TITLES}; X++));do
-			AGE=$(sed 's/ago .*/ago/' <<<${AGES[${X}]})
-			[[ -z ${AGE} ]] && continue
-			VID_LIST+="${X}|${SEARCHTERM}|${TITLES[${X}]}|${AGE}|${LINKS[${X}]}|${DURATIONS[${X}]}"
+		for K in ${KEYWORDS};do
+			fsub -iy ${K} ${_DOWNLOAD_DIR} >/dev/null 2>&1
+			[[ ${g_QRY_ENGINE} == 'rumble' ]] && fsub -y -t65 ${_DOWNLOAD_DIR} >/dev/null 2>&1
 		done
-	else # general search
-		msg_box "Channel name: \"${SEARCHTERM}\" not found.  Performing general search..."
-		g_SEARCH_TYPE=general
-		GEN_SEARCH=$(sed 's/ /%20/g' <<<${SEARCHTERM})
-		PG=$(wget -q -O - "https://rumble.com/search/all?q=${GEN_SEARCH}")
-		TITLES=("${(f)$(pup --charset utf8 '.video-item--title text{}' <<<${PG} | iconv -f utf-8 -t ascii//TRANSLIT | sed 's/|//g')}")
-		AGES=("${(f)$(pup --charset utf8 '.video-item--meta attr{datetime}' <<<${PG})}")
-		DURATIONS=("${(f)$(pup --charset utf8 '.video-item--duration attr{data-value}' <<<${PG})}")
-		LINKS=("${(f)$(pup --charset utf8 '.video-item--a attr{href}' <<<${PG})}")
-		CHANNELS=("${(f)$(pup --charset utf8 '.video-item--by-a attr{href}' <<<${PG})}")
+	}
 
-		for ((X=1; X<=${#TITLES}; X++));do
-			[[ ${CHANNELS[${X}]} =~ 'user' ]] && continue # experimental to avoid dups by users
-			AGE=$(sed 's/T.*//' <<<${AGES[${X}]})
-			CHANNEL=$(sed 's#^.*/##' <<<${CHANNELS[${X}]})
-			CHANNEL="${(C)SEARCHTERM} (${CHANNEL})"
-			VID_LIST+="${X}|${CHANNEL}|${TITLES[${X}]}|${AGE}|${LINKS[${X}]}|${DURATIONS[${X}]}"
+	reset_job () {
+		kill_job
+		msg_box -t.2 -x$((COORDS[X]+5)) -y$((COORDS[Y] + COORDS[W] -25)) "<m>Job Restarted<N>"
+	}
+
+	rumble () {
+		local SEARCHTERM=${@}
+		local -a AGES
+		local -a CHANNELS
+		local -a DURATIONS
+		local -a LINKS
+		local -a TITLES
+		local -aU VID_LIST=()
+		local AGE
+		local CHANNEL
+		local GEN_SEARCH
+		local LIVE
+		local PG
+		local MSG
+		local X
+		local NDX
+
+		PG=$(wget -q -O - "http://rumble.com/c/${SEARCHTERM}?page=1")
+
+		if [[ -n ${PG} ]];then # channel search
+			[[ ${_FAVORITE_ENGINE[${SEARCHTERM}]:l} == 'r' ]] && g_LIVE=false
+			[[ ${_FAVORITE_ENGINE[${SEARCHTERM}]:l} == 'rl' ]] && g_LIVE=true
+			[[ ${g_LIVE_OPT} == 'true' ]] && { [[ ${g_LIVE} == 'true' ]] && g_LIVE=false || g_LIVE=true }
+			[[ ${g_LIVE} == 'true' ]] && MSG="Searching for livestreams" || MSG="Searching for videos"
+			msg_box -c ${MSG}
+			LIVE=$(pup '.channel-subheader--menu-item attr{href}' <<<${PG} | grep "livestreams")
+			[[ ${g_LIVE} == 'true' && -n ${LIVE} ]] && PG=$(wget -q -O - "http://rumble.com${LIVE}")
+			[[ ${PG:l} =~ "no videos found" ]] && msg_box -c "<r>No livestreams<N> for ${SEARCHTERM}|Falling back to defaults..." && PG=$(wget -q -O - "http://rumble.com/c/${SEARCHTERM}?page=1")
+
+			g_SEARCH_TYPE=channel
+			TITLES=("${(f)$(pup --charset utf8 '.title__link text{}' <<<${PG} | tut blank_lines | iconv -f utf-8 -t ascii//TRANSLIT | sed 's/|//g')}")
+			AGES=("${(f)$(pup --charset utf8 '.videostream__data text{}' <<<${PG} | tut blank_lines | tr '[\012|\015]' '[ ]' | sed -e 's/comments /comments\n/g')}")
+			LINKS=("${(f)$(pup --charset utf8 'a.videostream__link attr{href}' <<<${PG})}")
+			DURATIONS=("${(f)$(pup --charset utf8 '.videostream__badge text{}' <<<${PG} | tut blank_lines)}")
+
+			for ((X=1; X<=${#TITLES}; X++));do
+				AGE=$(sed 's/ago .*/ago/' <<<${AGES[${X}]})
+				[[ -z ${AGE} ]] && continue
+				VID_LIST+="${SEARCHTERM}|${TITLES[${X}]}|${AGE}|${LINKS[${X}]}|${DURATIONS[${X}]}" # unique rows
+			done
+		else # general search
+			msg_box "Channel name: \"${SEARCHTERM}\" not found.  Performing general search..."
+			g_SEARCH_TYPE=general
+			GEN_SEARCH=$(sed 's/ /%20/g' <<<${SEARCHTERM})
+			PG=$(wget -q -O - "https://rumble.com/search/all?q=${GEN_SEARCH}")
+			TITLES=("${(f)$(pup --charset utf8 '.video-item--title text{}' <<<${PG} | iconv -f utf-8 -t ascii//TRANSLIT | sed 's/|//g')}")
+			AGES=("${(f)$(pup --charset utf8 '.video-item--meta attr{datetime}' <<<${PG})}")
+			DURATIONS=("${(f)$(pup --charset utf8 '.video-item--duration attr{data-value}' <<<${PG})}")
+			LINKS=("${(f)$(pup --charset utf8 '.video-item--a attr{href}' <<<${PG})}")
+			CHANNELS=("${(f)$(pup --charset utf8 '.video-item--by-a attr{href}' <<<${PG})}")
+
+			for ((X=1; X<=${#TITLES}; X++));do
+				[[ ${CHANNELS[${X}]} =~ 'user' ]] && continue # experimental to avoid dups by users
+				AGE=$(sed 's/T.*//' <<<${AGES[${X}]})
+				CHANNEL=$(sed 's#^.*/##' <<<${CHANNELS[${X}]})
+				CHANNEL="${(C)SEARCHTERM} (${CHANNEL})"
+				VID_LIST+="${CHANNEL}|${TITLES[${X}]}|${AGE}|${LINKS[${X}]}|${DURATIONS[${X}]}" # unique rows
+			done
+		fi
+
+		NDX=0
+		for X in ${VID_LIST};do
+			((NDX++))
+			VID_LIST[${NDX}]="${NDX}|${X}"
 		done
-	fi
 
-	if [[ ${g_SEARCH_TYPE} == 'general' ]];then
-		_LOCAL_LIST=("${(f)$(for L in ${VID_LIST};do echo ${L};done | sort -t'|' -k4.1,4.10 -r)}")
-	else
-		_LOCAL_LIST=(${VID_LIST})
-	fi
+		if [[ ${g_SEARCH_TYPE} == 'general' ]];then
+			_LOCAL_LIST=("${(f)$(for L in ${VID_LIST};do echo ${L};done | sort -t'|' -k4.1,4.10 -r)}")
+		else
+			_LOCAL_LIST=(${VID_LIST})
+		fi
 
-	# Display search results
-	if ! arr_is_populated "${_LOCAL_LIST}";then
-		return 1
-	fi
-	return 0
-}
+		[[ ${_DEBUG} -gt 1 ]] && dbg "${0}:${LINENO} _LOCAL_LIST count: ${#_LOCAL_LIST}"
+		[[ ${_DEBUG} -gt 1 ]] && dbg "${0}:${LINENO} TITLES: ${#TITLES}"
+
+		# Display search results
+		if ! arr_is_populated "${_LOCAL_LIST}";then
+			return 1
+		fi
+
+		return 0
+	}
 
 select_download () {
 	local SEARCHTERM=${1:=Unknown}
@@ -526,8 +545,10 @@ select_download () {
 	SEARCHTYPE=Videos
 	if [[ ${g_QRY_ENGINE:l} == 'rumble' && ${g_LIVE} == 'true' ]];then
 		SEARCHTYPE=Live
+		list_set_sort_cols 1 4 2 2 3 3 # age, author, title
 	elif [[ ${g_QRY_ENGINE:l} == 'youtube' && ${g_STRICT} == 'true' ]];then
 		SEARCHTYPE=${g_STRICT_MSG}
+		list_set_sort_cols '' # age, author, title
 	fi
 
 	#set headings
@@ -680,7 +701,7 @@ youtube () {
 
 	[[ ${g_STRICT} == 'true' ]] && g_STRICT_MSG="STRICT REJECTS:$(total_rejects ${NDX})" || g_STRICT_MSG=''
 
-	[[ ${_DEBUG} -gt 0 ]] && dbg "${0}:${LINENO} _LOCAL_LIST:${WHITE_FG}${#_LOCAL_LIST}${RESET}"
+	[[ ${_DEBUG} -gt 1 ]] && dbg "${0}:${LINENO} _LOCAL_LIST count: ${#_LOCAL_LIST}"
 
 	[[ ${_SMCUP} == 'false' ]] && do_smcup
 
